import assert from 'node:assert/strict';
import { DatabaseSync } from 'node:sqlite';
import { readFile, readdir } from 'node:fs/promises';
import worker from './dist/server/index.js';
const db = new DatabaseSync(':memory:');
for (const file of (await readdir('drizzle')).filter(name => name.endsWith('.sql')).sort()) db.exec(await readFile(`drizzle/${file}`,'utf8'));
const env = {DB:{prepare(sql){return {bind(...values){return {run:async()=>db.prepare(sql).run(...values)}},all:async()=>({results:db.prepare(sql).all()})}}}};
const origin = 'https://tracker.example';
const call = (method,body,path='/api/work-dates') => worker.fetch(new Request(origin+path,{method,headers:{origin,'content-type':'application/json'},...(body?{body:JSON.stringify(body)}:{})}),env);
const record={id:'test-1',date:'2026-09-15',lead:'Lead',supports:['Support A','Support B']};
assert.equal((await call('PUT',record)).status,200);
assert.deepEqual(await (await call('GET')).json(),[record]);
assert.equal((await call('PUT',{...record,id:'test-2'})).status,409);
assert.equal((await call('PUT',{...record,supports:['Lead','Support B']})).status,400);
assert.equal((await call('PUT',{...record,supports:['Support A']})).status,400);
assert.equal((await call('PUT',{...record,date:'2026-02-30'})).status,400);
assert.equal((await call('PUT',{...record,lead:'Updated lead'})).status,200);
assert.equal((await (await call('GET')).json())[0].lead,'Updated lead');
const crossOrigin = new Request(origin+'/api/work-dates',{method:'DELETE',headers:{origin:'https://elsewhere.example'}});
assert.equal((await worker.fetch(crossOrigin,env)).status,403);
assert.equal((await call('DELETE',null,'/api/work-dates?id=test-1')).status,200);
assert.deepEqual(await (await call('GET')).json(),[]);
for (const path of ['/','/tracker.html','/tracker.js','/tracker.css','/images/logo.png','/fonts/Futura-Regular.ttf']) assert.equal((await call('GET',null,path)).status,200);
console.log('Verified save, reload, edit, delete, date uniqueness, crew validation, request origin, and page assets.');
