import assert from 'node:assert/strict';
import { DatabaseSync } from 'node:sqlite';
import { readFile, readdir } from 'node:fs/promises';
import worker from './dist/server/index.js';
const db = new DatabaseSync(':memory:');
db.exec(await readFile('drizzle/0000_lying_thanos.sql','utf8'));
db.exec(await readFile('migrations/0002_entry_details.sql','utf8'));
const env = {DB:{prepare(sql){return {bind(...values){return {run:async()=>db.prepare(sql).run(...values)}},all:async()=>({results:db.prepare(sql).all()})}}}};
const origin = 'https://tracker.zahabu.co.ke';
const call = (method,body,path='/api/work-dates') => worker.fetch(new Request(origin+path,{method,headers:{origin,'content-type':'application/json'},...(body?{body:JSON.stringify(body)}:{})}),env);
const record={id:'test-1',date:'2026-09-15',eventName:'Test booking',workType:'Event',status:'Completed',lead:'Lead',supports:['Support A','Support B'],notes:'All clear',approvedBy:'Manager'};
assert.equal((await call('PUT',record)).status,200);
const saved = await (await call('GET')).json();
assert.equal(saved.length,1);
assert.deepEqual({...saved[0],createdAt:undefined,updatedAt:undefined}, {...record,createdAt:undefined,updatedAt:undefined});
assert.ok(saved[0].createdAt && saved[0].updatedAt);
assert.equal((await call('PUT',{...record,id:'test-2'})).status,409);
assert.equal((await call('PUT',{...record,supports:['Lead','Support B']})).status,400);
assert.equal((await call('PUT',{...record,supports:['Support A']})).status,400);
assert.equal((await call('PUT',{...record,date:'2026-02-30'})).status,400);
assert.equal((await call('PUT',{...record,lead:'Updated lead'})).status,200);
assert.equal((await (await call('GET')).json())[0].lead,'Updated lead');
const crossOrigin = new Request(origin+'/api/work-dates',{method:'DELETE',headers:{origin:'https://elsewhere.example'}});
assert.equal((await worker.fetch(crossOrigin,env)).status,403);
const publicOrigin = 'https://tracker-view.zahabu.co.ke';
const publicWrite = new Request(publicOrigin+'/api/work-dates',{method:'PUT',headers:{origin:publicOrigin,'content-type':'application/json'},body:JSON.stringify(record)});
assert.equal((await worker.fetch(publicWrite,env)).status,403);
assert.equal((await call('DELETE',null,'/api/work-dates?id=test-1')).status,200);
assert.deepEqual(await (await call('GET')).json(),[]);
for (const path of ['/','/tracker.html','/tracker.js','/tracker.css','/viewer.html','/viewer.js','/images/logo.png','/fonts/Futura-Regular.ttf']) assert.equal((await call('GET',null,path)).status,200);
console.log('Verified save, reload, edit, delete, date uniqueness, crew validation, request origin, and page assets.');
